#!/bin/bash

# Make the build directory
mkdir build

# Move to build directory
cd build

# Run CMake
echo "Running CMake..."
cmake ..

# Run make
echo "Running Make..."
make -j

# Return to root directory
cd ..
